//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Test__Playwright_ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Test__Playwright_.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uc-accept-all-button.
        /// </summary>
        internal static string acceptAllBtn {
            get {
                return ResourceManager.GetString("acceptAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;add-to-cart-sauce-labs-backpack&apos;].
        /// </summary>
        internal static string backpackAddtoCartBtn {
            get {
                return ResourceManager.GetString("backpackAddtoCartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;app&apos;]/header/div[4]/div/div/div/div/span[2]/div.
        /// </summary>
        internal static string douglasLogo {
            get {
                return ResourceManager.GetString("douglasLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        internal static string furWenDropdownId {
            get {
                return ResourceManager.GetString("furWenDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*/a[.=&apos;{0}&apos;].
        /// </summary>
        internal static string furWenXpath {
            get {
                return ResourceManager.GetString("furWenXpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschenk für.
        /// </summary>
        internal static string geschenkFurDropdownId {
            get {
                return ResourceManager.GetString("geschenkFurDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschenk für suchen.
        /// </summary>
        internal static string geschenkSearchBarPlaceholder {
            get {
                return ResourceManager.GetString("geschenkSearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flags.
        /// </summary>
        internal static string highlightsDropdownId {
            get {
                return ResourceManager.GetString("highlightsDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //following-sibling::div//a[.=&apos;{0}&apos;].
        /// </summary>
        internal static string highlightsXpath {
            get {
                return ResourceManager.GetString("highlightsXpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.douglas.de/de.
        /// </summary>
        internal static string mainURL {
            get {
                return ResourceManager.GetString("mainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand.
        /// </summary>
        internal static string markeDropdownId {
            get {
                return ResourceManager.GetString("markeDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marke suchen.
        /// </summary>
        internal static string markeSearchBarPlaceholder {
            get {
                return ResourceManager.GetString("markeSearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;app&apos;]/header/div[4]/div/div/div/span/span/div/div/nav/div/div/div/div[1]/div[3]/div/div/li/a.
        /// </summary>
        internal static string parfumeBtn {
            get {
                return ResourceManager.GetString("parfumeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;app&apos;]/div[1]/div/div[2]/div[1]/div[2]/div[2]/div[1]/div.
        /// </summary>
        internal static string parfumResultsLable {
            get {
                return ResourceManager.GetString("parfumResultsLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priceValue.
        /// </summary>
        internal static string priceDropdownId {
            get {
                return ResourceManager.GetString("priceDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classificationClassName.
        /// </summary>
        internal static string produktartDropdownId {
            get {
                return ResourceManager.GetString("produktartDropdownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktart suchen.
        /// </summary>
        internal static string produktartSearchBarPlaceholder {
            get {
                return ResourceManager.GetString("produktartSearchBarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [class=&apos;rc-scrollbars-view&apos;].
        /// </summary>
        internal static string scrollbarsView {
            get {
                return ResourceManager.GetString("scrollbarsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;usercentrics-root&apos;].
        /// </summary>
        internal static string shadowRoot {
            get {
                return ResourceManager.GetString("shadowRoot", resourceCulture);
            }
        }
    }
}
